INSERT INTO category (description) values ('American');
INSERT INTO category (description) values ('Italian');
INSERT INTO category (description) values ('Mexican');
INSERT INTO category (description) values ('Fast Food');
INSERT INTO unit_of_measure (description) values ('Teaspoon');
INSERT INTO unit_of_measure (description) values ('Tablespoon');
INSERT INTO unit_of_measure (description) values ('Cup');
INSERT INTO unit_of_measure (description) values ('Pinch');
INSERT INTO unit_of_measure (description) values ('Ounce');
INSERT INTO unit_of_measure (description) values ('Each');
INSERT INTO unit_of_measure (description) values ('Dash');
INSERT INTO unit_of_measure (description) values ('Pint');